### ISSUE TITLE
Delay in sip handling after upgrade to v0.32.1

### ISSUE THREAD

**Issue by Manoharmp** [emiago/diago#74]
In a test that bridges two calls to the same destination, upgrading sipgo has introduced a significant lag, both the bridge setup now takes much longer, and the listener hears the audio several seconds late.

Only difference in the example for bridge is that both the calls are incoming and the calls are bridged.

I did test with the previous version and it works fine.

**Comment by emiago** [comment]
Hi @Manoharmp . Maybe something is overlooked. I will check

**Comment by emiago** [comment]
Hi @Manoharmp. I have pushed this tool release now with latest diago 
https://github.com/emiago/diagox/releases/tag/v.1.2.0

Here is minimal setup 
```yaml
version: "2.4"

transports: 
  udp:
    transport: "udp"
    bind: 0.0.0.0
    port: 5060

routes:
  default: # Default context goes every call from all endpoints
    - id: ""
      match: "any"
      endpoint: bob

endpoints:
  alice:
    # Incoming options
    match: 
      type: "ip"
      values: ["127.0.0.1/24"]

  bob: # Address of record
    uri: "sip:localhost:5080" # Uri is for outgoing, but we only need host and port
```

Bridging:
UAS terminal: `gophone answer -l 0.0.0.0:5080 -media=echotest` 
UAC terminal: `gophone dial -l 127.0.0.1:0 -media=audio sip:bob@127.0.0.1:5060`

No delays or media setups in this case.

Please share your code example.
